"""
MOD-012: BackupTool — Configuration backup and rollback tool.
@author sub_agent_software_developer
@module MOD-012
@implements IFC-012-01, IFC-012-02
@depends None
@covers REQ-FUNC-020, REQ-NFUNC-005, REQ-NFUNC-006

Strategy Pattern: AbstractBackupTool (ABC) → MockBackupTool | TpLinkBackupTool (reserved)
"""

import time
from abc import ABC, abstractmethod
from typing import Any, Optional

from langchain_core.tools import BaseTool
from loguru import logger

from src.models.alert import DeviceAuth
from src.models.fix_plan import BackupResult, RollbackResult


# ────────────────────────────────────────────────────
# Mock running-config 模板
# ────────────────────────────────────────────────────

MOCK_RUNNING_CONFIG = """! Mock TP-Link Switch Running Configuration
! Generated by NetworkAgentDemo BackupTool
! Device: Core-SW-01
!
version 12.2
no service pad
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname Core-SW-01
!
boot-start-marker
boot-end-marker
!
enable secret 5 $1$mERr$hx5rVt7rPNoS4wqbXKX7m0
!
username admin privilege 15 secret 5 $1$mERr$hx5rVt7rPNoS4wqbXKX7m0
!
no aaa new-model
!
ip subnet-zero
ip routing
!
spanning-tree mode pvst
spanning-tree extend system-id
!
vlan 1
 name default
!
vlan 10
 name Production
!
interface GigabitEthernet0/1
 description Uplink to Distribution
 switchport access vlan 1
 switchport mode access
 no shutdown
!
interface GigabitEthernet0/2
 description Access Port
 switchport access vlan 1
 switchport mode access
 switchport port-security
 switchport port-security maximum 2
 switchport port-security violation restrict
 no shutdown
!
interface GigabitEthernet0/3
 description Server Port
 switchport access vlan 10
 switchport mode access
 no shutdown
!
interface GigabitEthernet0/4
 description Trunk to Core-SW-02
 switchport mode trunk
 switchport trunk allowed vlan 1,10
 no shutdown
!
interface Vlan1
 ip address 192.168.1.1 255.255.255.0
 no shutdown
!
interface Vlan10
 ip address 10.0.10.1 255.255.255.0
 no shutdown
!
ip default-gateway 192.168.1.254
!
line con 0
line vty 0 4
 login local
!
end"""


# ────────────────────────────────────────────────────
# Abstract Base Class
# ────────────────────────────────────────────────────

class AbstractBackupTool(BaseTool, ABC):
    """
    配置备份与回滚工具抽象基类。
    IFC-012-01: backup(device_ip, auth) → BackupResult
    IFC-012-02: rollback(device_ip, backup_id, auth) → RollbackResult
    """

    name: str = "config_backup"
    description: str = "Backup or rollback device running configuration"

    @abstractmethod
    def _run(
        self,
        device_ip: str,
        auth: DeviceAuth,
        operation: str,  # "backup" | "rollback"
        backup_id: str | None = None,
    ) -> BackupResult | RollbackResult:
        """Perform backup or rollback operation."""

    def run(
        self,
        tool_input: str = "",
        device_ip: str = "",
        auth: Optional[DeviceAuth] = None,
        operation: str = "backup",
        backup_id: Optional[str] = None,
        **kwargs: Any,
    ) -> str:
        """LangChain Tool 统一入口。"""
        if auth is None:
            auth = DeviceAuth(username="admin", password="")
        result = self._run(device_ip, auth, operation, backup_id)
        return str(result.model_dump())


# ────────────────────────────────────────────────────
# Mock Implementation (Demo)
# ────────────────────────────────────────────────────

class MockBackupTool(AbstractBackupTool):
    """
    Mock 实现 — backup 返回模拟 running-config，rollback 返回 success。
    """

    name: str = "config_backup"
    description: str = "Backup or rollback device running configuration (Mock)"

    def __init__(self) -> None:
        super().__init__()
        self._backup_store: dict[str, str] = {}  # backup_id → config

    def _run(
        self,
        device_ip: str,
        auth: DeviceAuth,
        operation: str = "backup",
        backup_id: str | None = None,
    ) -> BackupResult | RollbackResult:
        if operation == "rollback":
            return self._do_rollback(device_ip, backup_id, auth)
        else:
            return self._do_backup(device_ip, auth)

    def _do_backup(self, device_ip: str, auth: DeviceAuth) -> BackupResult:
        """IFC-012-01: 执行配置备份。"""
        import uuid

        backup_id = str(uuid.uuid4())
        config = MOCK_RUNNING_CONFIG.replace("Core-SW-01", device_ip)

        # 模拟拉取配置的延迟
        time.sleep(0.5)

        self._backup_store[backup_id] = config
        logger.info(f"[MockBackup] {device_ip}: backup created — backup_id={backup_id[:8]}...")

        return BackupResult(
            success=True,
            backup_id=backup_id,
            config=config,
        )

    def _do_rollback(
        self, device_ip: str, backup_id: str | None, auth: DeviceAuth
    ) -> RollbackResult:
        """IFC-012-02: 执行配置回滚。"""
        if backup_id is None:
            return RollbackResult(
                success=False,
                error="backup_id is required for rollback operation",
            )

        config = self._backup_store.get(backup_id)
        if config is None:
            return RollbackResult(
                success=False,
                error=f"Backup not found: {backup_id}",
            )

        # 模拟回滚延迟
        time.sleep(1.0)
        logger.info(f"[MockBackup] {device_ip}: rollback from backup_id={backup_id[:8]}...")

        return RollbackResult(
            success=True,
            output=f"Configuration restored from backup {backup_id[:8]}...\n"
                   f"Device {device_ip} rolled back successfully.\n",
        )


# ────────────────────────────────────────────────────
# TP-Link Implementation (Reserved)
# ────────────────────────────────────────────────────

class TpLinkBackupTool(AbstractBackupTool):
    """
    TP-Link 真实实现（预留）。
    Demo 阶段不实现真实 SSH 调用，_run() 抛出 NotImplementedError。
    """

    name: str = "config_backup_tplink"
    description: str = "Backup or rollback TP-Link switch configuration via SSH (Reserved)"

    def _run(
        self,
        device_ip: str,
        auth: DeviceAuth,
        operation: str = "backup",
        backup_id: str | None = None,
    ) -> BackupResult | RollbackResult:
        """
        [RESERVED] 后续阶段启用 TP-Link 真实 SSH 备份/回滚。
        使用 Netmiko:
          - backup: SSH 执行 show running-config
          - rollback: 将备份配置通过 SSH 逐行写回
        """
        raise NotImplementedError(
            "TpLinkBackupTool is reserved for future TP-Link integration. "
            "Use MockBackupTool for Demo phase."
        )


# ────────────────────────────────────────────────────
# Factory
# ────────────────────────────────────────────────────

def create_backup_tool(
    use_mock: bool = True,
    device_type: str = "MOCK",
) -> AbstractBackupTool:
    """
    工厂函数：根据 device_type 创建对应的备份工具实现。

    Args:
        use_mock: [DEPRECATED] 保留向后兼容，优先使用 device_type
        device_type: "MOCK" → MockBackupTool | "SIMULATOR" → SimulatorBackupTool

    REQ-FUNC-111: 工具工厂策略扩展 — 根据设备类型分发。
    """
    if device_type == "SIMULATOR":
        from src.tools.simulator_backup_tool import SimulatorBackupTool
        return SimulatorBackupTool()

    if not use_mock:
        return TpLinkBackupTool()

    return MockBackupTool()
